### ISSUE TITLE
Only binary file works well.

### ISSUE THREAD

**Issue by ACKET2009** [Vasil-Pahomov/Liana#14]
Hello!
I has compile the ino-file, but the lights always drop the colors to blue/green or red/blue combinations,,, it is not depend on the power supply - the battery power bank show the same results: one time work good, another - only 2 colors mode,,, And no web page on the interface. While I has download the bin file and write it to esp all becomes fine... What can be wrong with compilation?

**Comment by Vasil-Pahomov** [comment]
Not sure what the problem may be. What board do you have? Are you working within Arduino IDE? If so, did you do all the setup correctly (like it's described in https://dzone.com/articles/programming-the-esp8266-with-the-arduino-ide-in-3)?

**Comment by ACKET2009** [comment]
Hello! 
The ESP8266 mini
Yes Arduino IDE
The sketch has compiled correctly, without errors and it work, but not perfect -  drop colors after the initialisation, as I already write and can not to open the web interface at the controller ip... while resetting or reconnecting the 5v some times - all of the colors apears... I do not understand why... I use the same settings of the board in IDE as for mclighting lights:
"
Set the CPU frequency to 80 MHz
Set the Flash Size to "4M (1M SPIFFS)". <-- Double check this!
Set the upload speed to 115200 (you could try to set it higher, but it could cause problems).
Select the right COM port.
Set "IwIP Variant" to "v2 Higher Bandwidth".
"
The details is here:
[MCLighting](https://github.com/toblum/McLighting/wiki/Software-installation)

**Comment by Vasil-Pahomov** [comment]
Can you open the port monitor at 115200 baud and paste what you see there?
BTW we can go on in Russian if you wish :)

**Comment by ACKET2009** [comment]
Да, здравствуйте!
Сегодня прошил последнюю версию. 
По результату проверки - контроллер к Wi-Fi подключился, доступ к веб-страничке есть. То есть эта часть заработала (раньше была проблема). Но при подключении, проходит инициализация, с пробегающими огнями и мерцанием разноцветными огнями с переходом в белый, затем начинают переключаться режимы, которые почти всегда работают не в цвете, какие-то мутные сочетания пар цветов, то красно синего оттенка, то сине-зелёного. При нажатии ресет, почти всегда всё становится нормально. Так вот при прошивке бинарного варианта, при включении таких проблем не возникало и цвета сразу все были на месте, на mclighting с этой же гирляндой и контроллером тоже всё хорошо работает. Поэтому, возможно, что-то с кодом...

**Comment by Vasil-Pahomov** [comment]
Это странно, у нескольких человек компилится всё и работает нормально. Попробуйте переустановить Arduino, и ставьте версию 2.5.2 плат ESP. С последней 2.6.0 не компилируется (пока не разбирался в причинах)

**Comment by ACKET2009** [comment]
Установлена 2.5.2, так и есть. Странно... не побеждается. У меня несколько плат Wemos mini и на всех такая проблема. Она всё-же не в железе. Ошибок при компиляции нет. Может библиотеки какие-то не корректные... Но предыдущая версия на ардуино нано замечательно работала... Wemos меньше с большими ресурсами и вай-фаем, поэтому конечно же предпочтительнее, но никак не идёт так, чтобы без проблем. И хорошо бы, как в mclighting сделать настройку вай-фай при подключении, конечно

**Comment by ACKET2009** [comment]
Upd. Здравствуйте! На гирлянде экспериментировал с ручными режимами, выяснил, что в режиме огонь гирлянда горит зелёным цветом, в то время, как лента горит красным. Может где-то нужно переключить под тип гирлянды RGB-->GRB? Только я не нашёл как это сделать...

**Comment by ACKET2009** [comment]
Upd. Похоже сине-зелёные оттенки, красно-синие, или красно-зелёные, при включении возникают из за старта гирлянды в режиме огонь, жара и прочих. При переключении в RGB из управляющей программы цвета появляются. Можно как-то сделать, чтобы режим RGB стартовал всегда в приоритете?

**Comment by Vasil-Pahomov** [comment]
Вообще это странно, потому что при смене палитры никаких аппаратных настроек не производится, это чисто программная вещь. Возможно что-то с таймингами. Я бы попробовал поиграться вторым параметром в конструкторе NeoPixelBus (https://github.com/Vasil-Pahomov/Liana/blob/master/anim.cpp#L7), например вместо NeoEsp8266Uart1800KbpsMethod поставил бы NeoEsp8266Uart0800KbpsMethod, и другие режимы можно попробовать из https://github.com/Makuna/NeoPixelBus/wiki/ESP8266-NeoMethods.
Чтобы эффекты стартовали с палитры  RGB, нужно при инициализации палитры выставить 0 вместо случайного значения: https://github.com/Vasil-Pahomov/Liana/blob/master/Liana.ino#L33, вписать там `int paletteInd = 0;` вместо `int paletteInd = random(PALS);`

**Comment by ACKET2009** [comment]
int paletteInd = 0; - помогло, теперь стартует нормально всегда, а раньше с какой запускалось, так и работало, пока вручную не переключишь.
