### ISSUE TITLE
Перезагрузки

### ISSUE THREAD

**Issue by negativ72rus** [Vasil-Pahomov/Liana#16]
При попытке зайти в веб-интерфейс нода перезагружается. Питание от БП 5В 2,1А (пока без ленты), куда смотреть?

**Comment by negativ72rus** [comment]
При питании от минвелл 5В 5А картина та же, в сериал порт пишет:
Exception (3):
epc1=0x40214384 epc2=0x00000000 epc3=0x00000000 excvaddr=0x40248cd7 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffcf0 end: 3fffffc0 offset: 01a0
3ffffe90:  40248cd7 3fff0bc4 00000000 4020ebb0  
3ffffea0:  00000000 ff006576 3fff0b9c 40201056  
3ffffeb0:  00000000 00000000 ffff0b9c 40206690  
3ffffec0:  00000000 402066a0 3fff0b9c 401000a9  
3ffffed0:  3fff0b9c 3ffee908 3fffff00 40207292  
3ffffee0:  00000000 00000000 fffee8c4 4020e718  
3ffffef0:  3fff0b9c 3ffee908 3ffee8c4 4020731d  
3fffff00:  0000002f 00000000 00000000 00000000  
3fffff10:  ff2f5054 00000000 4bc6a7f0 00000000  
3fffff20:  3ffee8ec 3ffee978 00000001 6dd2f1a9  
3fffff30:  00000001 3ffe84dc 00000000 0000000f  
3fffff40:  00000000 4bc6a7f0 0000a2b6 3ffe84dc  
3fffff50:  00000001 3ffee8ec 3ffee8c4 40207570  
3fffff60:  3ffee9b8 3ffe84dc 4020f484 3fffefa0  
3fffff70:  00000000 00000000 3ffef180 4020f566  
3fffff80:  3ffee9b8 00000000 3ffef180 402019a2  
3fffff90:  00000000 00000000 00000001 3ffef1b0  
3fffffa0:  3fffdad0 00000000 3ffef180 4020f534  
3fffffb0:  feefeffe feefeffe 3ffe856c 401007c5  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v8b899c12

**Comment by Vasil-Pahomov** [comment]
Скорее всего проблема не в питании. 
Какая плата?
Другие скетчи с web-интерфейсом работают?
Бинарник заливать пробовали, как с ним?

**Comment by negativ72rus** [comment]
@Vasil-Pahomov 
плата nodemcu v2 (esp12e)
Другие скетчи с wifi работают, с веб-мордами не пробовал ничего.
А как заливать бинарник?

**Comment by negativ72rus** [comment]
Залил пример от mDNS - все работает.

**Comment by negativ72rus** [comment]
@Vasil-Pahomov 
Прошил бинарник - все работает.
Какие должны быть параметры платы для загрузки?
Сейчас вот так:
![image](https://user-images.githubusercontent.com/12546951/68384077-a8ec8e80-0178-11ea-8dde-757731f070f5.png)

**Comment by Vasil-Pahomov** [comment]
Вот такие параметры платы у меня
![image](https://user-images.githubusercontent.com/15260215/68384387-90747800-0168-11ea-8459-9608f3289b07.png)

**Comment by negativ72rus** [comment]
@Vasil-Pahomov 
Хмм, видимо что-то все же у меня криво собирается или заливается... Потыкаю в параметры сегодня вечерком. Хотелось бы на свою сеть зашить модуль )
Спасибо.

**Comment by Vasil-Pahomov** [comment]
Я планирую доработать скетч так, чтобы через морду можно было подключаться к внешней сети (а не зашивать логин с паролем в скетч). Есть ещё один повод ускориться :)

**Comment by negativ72rus** [comment]
@Vasil-Pahomov 
О, это да, было бы удобно. Тогда можно и бинарник лить, таким же криворуким как я )))))

**Comment by negativ72rus** [comment]
Оу, уже все обновилось? :-)
