### ISSUE TITLE
Пожелания и комментарии

### ISSUE THREAD

**Issue by ACKET2009** [Vasil-Pahomov/Liana#18]
Добрый день!
Вчера скачал обновлённый вариант прошивки с возможностью смены настроек Wi-Fi программно.
      Проблема возникла при попытке записать spiffs, писало, что python не установлен, нашёл его расположение в папке с платами (требовался файл python3.exe, пришлось создать хардлинк у меня был только python.exe и создать пути в операционке к этой папке, ошибка пропала, но ничего не происходило. У меня версия arduino IDE 1.8.10 и версия библиотеки плат 8266 на тот момент была 2.5.2. В общем побился-побился, не выходит. Сохранил свой бинарник и попробовал залить с приложенным для spiffs, но после прошивки гирлянда почему-то не стартанула... Тогда я решился обновить платы до версии 2.6.2, после чего питон переустановился и запись spiffs заработала, так же прошил и плату. Теперь всё работает отлично.
     По поводу пожеланий - я думаю, что было бы уместно и не очень сложно теперь, переименовать страничку из настроек wi-fi просто в настройки и добавить туда поле для смены сетевого имени, переключение режимов цвета (RGB/GRB и т.п.) и количество диодов в ленте. А из глобальных - конечно же добавить больше эффектов, возможно не все, но самые интересные из порядка 50 имеющихся в наборе neopixel где по одному бегают, навстречу друг другу, смена направлений и цвета заполнения гирлянды и т.п. Может быть на основную страницу управления эффектами добавить управление яркостью и скоростью (в идеале для каждого эффекта и сохранять для авто-плэя :))... мечты
Вообще большущее спасибо!!! внукам очень нравится!

**Comment by ACKET2009** [comment]
P.S. строчки в liana.ino уже не актуальны...
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//!! Be sure to set up your WiFi network name and password in the wifi.ino file !!
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ACKET2009** [comment]
Ещё не могу понять - цветовые шаблоны в авторежиме сменяются, или только при включении назначаются? Если только при включении, может, как пожелание, тогда ещё выключатель добавить для включения автосмены - побольше комбинаций получится, только там алгоритм какой нибудь, чтобы лёд и огонь не очень часто выскакивали...

**Comment by Vasil-Pahomov** [comment]
Спасибо за пожелания! У самого похожие были, и ещё много других идей, но к сожалению это только хобби, и времени на всё не хватает. Тем не менее постараюсь учесть.
Про цветовые шаблоны замечание "в точку" - задумка была менять их случайно в авторежиме, но из-за бага они не менялись. Исправление залил.

**Comment by Vasil-Pahomov** [comment]
Залил в мастер версию с возможностью настройки количества светодиодов.

**Comment by ACKET2009** [comment]
Супер! теперь работает смена цветовых режимов! Стало гораздо интереснее!

**Comment by ACKET2009** [comment]
Зашил сегодня последнюю версию с установкой количества светодиодов. 
1) Я переделываю под свою ленту строчку:
NeoPixelBus<NeoGrbFeature, NeoEsp8266Uart1800KbpsMethod>* strip; у меня она выглядит, как:
NeoPixelBus<NeoRgbFeature, NeoEsp8266Dma800KbpsMethod>* strip;
не совсем удобно дальше по скетчу повторно менять...
2) Появились 2 пункта выбора wi-fi и led, но пропал выбор режимов работы :)
3) отзывается только по айпи, по liana.local - не видится в сети

**Comment by Vasil-Pahomov** [comment]
Баг с пропаданием выбора режимов должен быть исправлен (буквально только что фикс залил, правда проверить не могу). По доступу через liana.local посмотрю позже, сейчас платы нет

**Comment by ACKET2009** [comment]
2 - всё появилось!
А режим Ota - предполагается прошивка по воздуху?

**Comment by Vasil-Pahomov** [comment]
Исправил проблему с mDNS (теперь работает http://liana.local)
OTA - да, это прошивка по WiFi. Я когда-то включал в скетч, но всё никак не дойду доделать, более приоритетные вещи есть. Мне кажется это будет иметь смысл при наличии сервера в Интернете, но до этого мне ещё далеко.

**Comment by ACKET2009** [comment]
> Исправил проблему с mDNS (теперь работает http://liana.local)
Перепрошил всё полностью и скетч и вайфай и спиф - не сопоставляет в сети айпи с этим именем - не находит...

**Comment by DisDis** [comment]
У меня проблема с тем что после заливки мастера, веб морда не работает , при старте пишет пишет 
`(start)Config read error
`
SPIFFS залит
```
[SPIFFS] data    : /home/dis/workspace/Liana/data
[SPIFFS] size    : 1004
[SPIFFS] page    : 256
[SPIFFS] block   : 8192
/wifi.htm
/index.htm
/s.css
/setup.htm
/config.json
[SPIFFS] upload  : /tmp/arduino_build_973211/Liana.spiffs.bin
[SPIFFS] address  : 0x300000
[SPIFFS] reset    : nodemcu
[SPIFFS] port     : /dev/ttyUSB0
[SPIFFS] speed    : 921600
[SPIFFS] python   : python3
[SPIFFS] uploader : /home/dis/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/upload.py
```

**Comment by ACKET2009** [comment]
А Вас не смущает, что в описании адрес должен быть 0х100000, а у Вас 0х300000

**Comment by DisDis** [comment]
Смущает, проблема в том что аплоадер не конфигурируется

**Comment by DisDis** [comment]
Блин оказалось что бы [SPIFFS] address  : 0x100000 надо ставить Flash size: 4M(3M SPIFFS) :(

**Comment by DisDis** [comment]
Не помогло(

**Comment by DisDis** [comment]
Причина была в том что через плагин не заливалась дата на ЕСПиху, только через командную строку 
`esptool --port /dev/ttyUSB0 write_flash 0x100000 ~/Liana.spiffs.bin`
Видимо это только под линуксом.

**Comment by ACKET2009** [comment]
> > Исправил проблему с mDNS (теперь работает http://liana.local)
> 
> Перепрошил всё полностью и скетч и вайфай и спиф - не сопоставляет в сети айпи с этим именем - не находит...
А где копать нужно?

**Comment by DisDis** [comment]
@ACKET2009 у меня и до этого работало, и по ип и по имени http://liana.local .
```
ping liana.local
PING liana.local (192.168.1.163) 56(84) bytes of data.
64 bytes from 192.168.1.163 (192.168.1.163): icmp_seq=1 ttl=255 time=107 ms
64 bytes from 192.168.1.163 (192.168.1.163): icmp_seq=2 ttl=255 time=1.50 ms
```

**Comment by DisDis** [comment]
@ACKET2009 по ип должно работать в любом случае. если нет, то вы не в сети где гирлянда.

**Comment by ACKET2009** [comment]
c:\>ping liana.local
При проверке связи не удалось обнаружить узел liana.local.
Проверьте имя узла и повторите попытку.

c:\>ping 192.168.1.6

Обмен пакетами с 192.168.1.6 по с 32 байтами данных:
Ответ от 192.168.1.6: число байт=32 время=252мс TTL=255
Ответ от 192.168.1.6: число байт=32 время=62мс TTL=255
Ответ от 192.168.1.6: число байт=32 время=77мс TTL=255
Ответ от 192.168.1.6: число байт=32 время=97мс TTL=255

Статистика Ping для 192.168.1.6:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 62мсек, Максимальное = 252 мсек, Среднее = 122 мсек
Гирлянда находится на пингуемом адресе, но по имени не откликается значит в днс его нет

**Comment by DisDis** [comment]
@ACKET2009 в винде с 10 версии есть поддержка. https://stackoverflow.com/questions/23624525/standard-mdns-service-on-windows

**Comment by ACKET2009** [comment]
Ну шикарно - очень много сделали! Единственное - у меня вебморда не корректно отображается теперь - точки выбора россыпью вдоль центральной вертикали, а надписи где-то далеко справа... наверное под мобильную версию заточено, а я с компьютера захожу

**Comment by ACKET2009** [comment]
Да, посмотрел - с телефона вообще здорово!

**Comment by Vasil-Pahomov** [comment]
Странно, у меня и на компе просто растягивается, но не рассыпается. А вообще да, под десктопы не рассчитывал. Можно лайфхаком воспользоваться в Chrome - включить режим отображения как на мобилках F12, затем Ctrl+Shift+M

**Comment by ACKET2009** [comment]
тут вообще странная история - ничего не получалось, отображается только вертикальные точки и надписи, никаких картинок (браузер опера мобильная и samsung internet). Вчера с другой платой с разными прошивками игрался, вроде было - подключаю, всё есть. Пытаюсь в свою текущую, что на ёлке залить - ничего не показывает, только в майкрософт эдже показывает. фантастика какая-то... Уже и бинарник лил и так и менял платы с лолин на ноде... ниччо не понимаю...
в чём разница-то??

**Comment by ACKET2009** [comment]
А дело как то связано было с ай-пи адресом, возможно куки какие-то к нему приписались, сменил ай-пи, везде заработало. приложение самсунг-интернет снёс - ставил только для режима магии

**Comment by DisDis** [comment]
Предположу что это кэш. И надо было пробовать в инкогнито открывать.

**Comment by ACKET2009** [comment]
А, если неверно введены данные вай-фай соединения и в устройствах роутера не появляется гирлянда и в списке вай-фай сетей её нет, как-то сбросить можно настройки без повторной прошивки?

**Comment by Virgisva** [comment]
Здравствуйте, подскажите пожалуйста а как сделать чтобы при выборе определённого эффекта он сохранялся пока его не поменять на новый, а то получается выбрал какой то понравившийся эффект а он спустя некоторое время сам меняется и так по кругу.

**Comment by DiRH** [comment]
Присоединяюсь к вопросу выше, хочется чтобы настройки запоминались. Сейчас они не несут функциональности, т.к. пришел в веб-интерфейс, сменил эффект, а толку нет - через минуту другую анимации снова идут поочередно.

**Comment by Vasil-Pahomov** [comment]
Добавил возможность выключать отдельные эффекты и палитры из перебора. Фиксацию эффекта можно сделать через эту фичу, оставив включённым нужный эффект/палитру.
