### ISSUE TITLE
Управление не из браузера.

### ISSUE THREAD

**Issue by BarkanovSergey** [Vasil-Pahomov/Liana#21]
Подскажите, пожалуйста, как можно управлять гирляндой не через браузер? Хочется встроить управление в Majordomo.

**Comment by Vasil-Pahomov** [comment]
Технически такая возможность есть прямо сейчас при подключении через WebSockets. Собственно так web-клиент и работает. Но не знаю, умеет ли Majordomo так подключаться и управлять.
По-хорошему нужно прикрутить управление через MQTT или хотя бы через HTTP-запросы, но пока нет времени :(
В связи с этим вопрос - какие функции предполагается задействовать через Majordomo? Про включение и выключение понятно, но что ещё может понадобится?

**Comment by BarkanovSergey** [comment]
Как минимум, On/OFF.  В идеале, выбор режима...

**Comment by DjPrizrak** [comment]
Лучше через MQTT.
Включение, яркость, режим.
Было бы супер.

**Comment by BarkanovSergey** [comment]
И, глобально, скорость эффектов.

**Comment by Vasil-Pahomov** [comment]
Сделал базовое управление через MQTT
