### ISSUE TITLE
Уменьшение яркости стартового эффекта (БП уходит в защиту)

### ISSUE THREAD

**Issue by vovka36** [Vasil-Pahomov/Liana#23]
Мой блок питания на 12В 2А во время стартового эффекта, когда ярко мигают белым все светодиоды, уходит в защиту, т.к. ток потребления достигает 3,5А. ВСЕ другие эффекты с максимальной яркостью  работают отлично, максимальный ток потребления не превышает 1,1 - 1,2А.
Нужна возможность снизить яркость именно первого эффекта, в файле или через настройки.

**Comment by Vasil-Pahomov** [comment]
Хорошее замечание, спасибо! Временно можете уменьшить яркость стартового эффекта, заменив все девять  констант 255 на меньшее число (например 128) в файле https://github.com/Vasil-Pahomov/Liana/blob/master/anim_start.cpp.

**Comment by DisDis** [comment]
по умолчанию яркость выставляется из конфига.
