### ISSUE TITLE
@Vasil-Pahomov Need your approve to use your code in the expurna project

### ISSUE THREAD

**Issue by ElderJoy** [Vasil-Pahomov/Liana#24]
Hi Vasil,
Sorry for this, but it is only one way that I found to contact with you. I used your code (don't sure the latest one, possibly it was even old Arduino version), refactor it a bit and now want to push as module to xoseperez/espurna ESP8266 project. It is non-commercial open source project.
https://github.com/xoseperez/espurna/pull/2408 - this is the pull request.
There is licensing question arise now. Unfortunately, I didn't found any license in your repository or in the code.
So, I kindly ask your permission to use module, originally derived by your library in xoseperez/espurna project.
You can contact to me by email dblinov76@gmail.com or just write your message in the pull-request discussion under this comment: https://github.com/xoseperez/espurna/pull/2408#pullrequestreview-556375699
Thank you!

**Comment by Vasil-Pahomov** [comment]
Will contact you via email
