### ISSUE TITLE
Не сохраняются в EPROM параметры Wi-Fi

### ISSUE THREAD

**Issue by darts2020** [Vasil-Pahomov/Liana#32]
После обновления от 18.11.2021г. не сохраняются данные беспроводной сети. После перезагрузки контроллер постоянно поднимает АР.

**Comment by Witska** [comment]
Подтверждаю те же симптомы.

**Comment by Witska** [comment]
Нашел решение, подключайся к вайфаю, затем снова повторно подключис.

**Comment by Vasil-Pahomov** [comment]
Вроде исправил, просьба проверить

**Comment by Witska** [comment]
Теперь все хорошо, для компиляции необходимо добавлять в libdeps EspHtmlTemplateProcessor.

**Comment by darts2020** [comment]
Теперь всё нормально. Спасибо!
