### ISSUE TITLE
Mqtt не работает

### ISSUE THREAD

**Issue by DjPrizrak** [Vasil-Pahomov/Liana#33]
на последних бинарных прошивках mqtt не работает

**Comment by igorpoliakov-od** [comment]
Аналогично. Собирал сам билд для d1 mini, и никак не могу запустить управление через mqtt.

**Comment by Vasil-Pahomov** [comment]
Вроде исправил, попробуйте сейчас.

**Comment by igorpoliakov-od** [comment]
в логах вижу что к mqtt коннектится, но пока корректно отрабатывает только команду "on", остальные пишет что неизвестны:

Attempting MQTT connection to 192.168.88.29:1883, login=mqtt, pass=mqtt...connected
anim->(pixiedust)
(start)MQTT command unknown: length=12, payload=brightness=3c1
MQTT command unknown: length=14, payload="brightness=3"
MQTT command unknown: length=15, payload="brightness=3 "␄mqtt
MQTT command unknown: length=15, payload="brigthness=3 "␄mqtt


также нужно в коде исправить команду  "brigthness" на "brightness"

**Comment by igorpoliakov-od** [comment]
Проверил, теперь коннектится и командлы принимает. Правда так и не понял как адресоваться к конкретной гирлянде а не к топику.

И еще нужно в коде иправить опечатьку в команде "brigthness" на  "brightness"

**Comment by Vasil-Pahomov** [comment]
Поддержка MQTT делалась в качестве эксперимента, сам я её не использую и потребностей не очень понимаю...
Задумка была в том, что для каждой гирлянды создаётся отдельный топик.
Синтаксис команды исправил, спасибо!

**Comment by igorpoliakov-od** [comment]
Синтаксис исправлен только в одном месте, а там еще и для up/down тоже нужно исправить. По нужности MQTT: использую для умного дома, который сам включает гирлянду утром, а ночью выключает, плюс снижает яркость после 23. Удобно.

**Comment by Vasil-Pahomov** [comment]
Спасибо @Witska, синтаксис для up/down исправлен (https://github.com/Vasil-Pahomov/Liana/pull/37)

**Comment by DisDis** [comment]
@igorpoliakov-od а как вы собирали для D1 mini? у меня плата запускается, светодиоды работают, а вот подключение к WIFI не работает, плата переходит в режим AP и всё:( на ESP32 всё пашет как нужно. Раньше стояла на этой же плате (D1 mini) прошивка двух годичной давности WiFi работал.(читал что Arduino-ESP ядро 3.х приводит к такому багу)

**Comment by DisDis** [comment]
@igorpoliakov-od я добавил поддержку d1 mini в список платформ для сборки в platformio.ini
