### ISSUE TITLE
Цветовой режим ленты

### ISSUE THREAD

**Issue by Neybr** [Vasil-Pahomov/Liana#39]
Добрый день.
С наступившим Вас новым годом! Третий год уже светит гирлянда на елке, но решил обновить саму ленту и столкнулся с проблемой отсутствия режима ленты BGR. Возможно добавить?
Скачал VSCode но ничерта в нем не пойму, а строк с режимами нашел в нескольких местах, чего дальше делать, если даже добавлю новую строку - не знаю...

**Comment by DisDis** [comment]
@Neybr можно добавить только NeoBrgFeature
по аналогии
https://github.com/Vasil-Pahomov/Liana/blob/master/src/NeoPixelWrapper.cpp#L183
добавив   
`NeoPixelBus<NeoBrgFeature,NP_METHOD>*  _pBrg;`
ну и надо сделать по аналогии с _pRbg, поправив всюду условия.

**Comment by Neybr** [comment]
Это я как раз и нашел.
Но я не прораммер и как дальше мои изменения превратить в прошивку, чтоб залить в esp не знаю.)

**Comment by DisDis** [comment]
@Neybr  я уже сделал MR, ждите когда автор @Vasil-Pahomov зальёт все изменения в мастер и тогда всё появится в интерфейсе. Либо возьмите версию из моей репы из ветки support_BGR.

**Comment by Neybr** [comment]
@DisDis вижу в вашем репозитории "Support BRG", но это немного не то. Лента - BGR.

**Comment by DisDis** [comment]
@Neybr библиотека поддерживает только такой формат, конвертировать конечно можно поменяв канал, но для начала проверте этот вариант

**Comment by Neybr** [comment]
Да в таком формате вообще белеберда, Все зеленое)) В прошлом было все
синее. Короче не вариант, теплых цветов практически нет.
Так как я уже научился собирать из VSC, может тогда найти палитры и там R
поменять с B, а запускать потом в обычном формате RGB?
В веб морду никогда не смотрю - включил и погнало 24/7.

Откуда возникла проблема - раньше стояла лента быстрого монтажа 2811 с
правильным RGB и горе не знала 2 года. Потом я ее встроил в потолок
матрицей, а на елку купил новомодную 2812, вот такую:
[image: image.png]
А у нее как раз оказалось BGR. В WLED поддержка таких цветов есть, ну я и
не доставая с гаража гирлянду, думал, что и тут есть. Но блин не все так
просто...
А холодные оттенки на гирлянде уже задолбали если честно.(
Вот такая грустная история(

вт, 4 янв. 2022 г. в 21:14, Igor Demyanov ***@***.***>:

**Comment by DisDis** [comment]
@Neybr не совсем верно, надо включить режим BRG, и в коде анимаций поменять местами r,g каналы, не забывайте поменять каналы и при создании цвета  и во всех вызовах, ну а дальше всё должно заработать. начните с одной анимации для примера. Удачи

**Comment by Vasil-Pahomov** [comment]
> Да в таком формате вообще белеберда, Все зеленое)) В прошлом было все синее. ... А холодные оттенки на гирлянде уже задолбали если честно.( Вот такая грустная история( >:
Странно, такое чувство что у вас не все каналы в принципе работают. Попробуйте выберите красно-зелёно-синюю палитру (самую верхнюю) - должны быть все цвета, пусть и перепутанные.
Вы точно уверены что у Вас цвета BGR?

**Comment by Neybr** [comment]
> Вы точно уверены что у Вас цвета BGR?

Добрый день.
Абсолютно точно уверен.
Перепутаны красный и синий.
Лично проверял одновременно с лентой 2811 на которой режим RGB.

**Comment by Vasil-Pahomov** [comment]
Основная проблема добавить режим BGR в том, что используемая библиотека NeoPixelBus не даёт этого режима "из коробки", в отличие от остальных режимов. Пока не знаю, как правильно сделать, не хочется в основном коде лепить костыли для поддержки режима.

**Comment by Vasil-Pahomov** [comment]
@Neybr вроде нашёл минимально костыльный способ. Обновил бинарники, попробуйте с ними, пожалуйста.

**Comment by Neybr** [comment]
@Vasil-Pahomov Огромное, человеческое спасибо!!!
Все работает как надо!

Всем, кто купил [набравшие в этом году популярность гирлянды](https://smartlight.me/image/cache/catalog/products/led/girlyanda/ws2812b/H77975b09e89e4fce8e165aa4d123d7aeI-1200x800.jpg) будут довольны правильными цветами, как теперь и я :)
Еще раз спасибо!
