### ISSUE TITLE
Эффект "Вспышки" не поддерживает 300 светодиодов

### ISSUE THREAD

**Issue by DisDis** [Vasil-Pahomov/Liana#44]
![PXL_20220111_101623640](https://user-images.githubusercontent.com/87201/148924468-df3382ed-3ed1-46b4-8fe7-528b91beb180.jpg)
Последние 50 из 300 светодиодов неверно работают.

**Comment by Vasil-Pahomov** [comment]
Похоже, наследие Arduino сказывается. Поменял byte на int, попробуйте, пожалуйста.

**Comment by DisDis** [comment]
Да всё работает.
